USE mysql_project_db;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE deck (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  deck_name VARCHAR(100) NOT NULL
  card_name VARCHAR(100) NOT NULL,
  image VARCHAR(100) NOT NULL,
  description TEXT
);