USE mysql_project_db;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE mycollections (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  card_name VARCHAR(100) NOT NULL,
  image VARCHAR(100) NOT NULL,
  date_of_collection DATE NOT NULL DEFAULT '1900-01-01'
);